module.exports = (function() {
    const __MODS__ = {};
    const __DEFINE__ = function(modId, func, req) { const m = { exports: {}, _tempexports: {} }; __MODS__[modId] = { status: 0, func, req, m }; };
    const __REQUIRE__ = function(modId, source) { if (!__MODS__[modId]) return require(source); if (!__MODS__[modId].status) { const m = __MODS__[modId].m; m._exports = m._tempexports; const desp = Object.getOwnPropertyDescriptor(m, "exports"); if (desp && desp.configurable) Object.defineProperty(m, "exports", { set (val) { if (typeof val === "object" && val !== m._exports) { m._exports.__proto__ = val.__proto__; Object.keys(val).forEach((k) => { m._exports[k] = val[k]; }); } m._tempexports = val; }, get () { return m._tempexports; } }); __MODS__[modId].status = 1; __MODS__[modId].func(__MODS__[modId].req, m, m.exports); } return __MODS__[modId].m.exports; };
    const __REQUIRE_WILDCARD__ = function(obj) { if (obj && obj.__esModule) { return obj; } else { const newObj = {}; if (obj != null) { for (const k in obj) { if (Object.prototype.hasOwnProperty.call(obj, k)) newObj[k] = obj[k]; } } newObj.default = obj; return newObj; } };
    const __REQUIRE_DEFAULT__ = function(obj) { return obj && obj.__esModule ? obj.default : obj; };
    __DEFINE__(1_691_668_914_749, function(require, module, exports) {
        !function(t, e){typeof exports==="object"&&module!==undefined?module.exports=e():(typeof define==="function"&&define.amd?define(e):(t=typeof globalThis==="undefined"?t||self:globalThis).dayjs=e());}(this, (() =>{const $=/^(\d{4})[-/]?(\d{1,2})?[-/]?(\d{0,2})[T\s]*(\d{1,2})?:?(\d{1,2})?:?(\d{1,2})?[.:]?(\d+)?$/i; const a="day"; const c="month"; const d="date"; const D={}; const e=6e4; const f="quarter"; let g="en"; const h="year"; const i="second"; const l="Invalid Date"; const M={ name:"en", weekdays:"Sunday_Monday_Tuesday_Wednesday_Thursday_Friday_Saturday".split("_"), months:"January_February_March_April_May_June_July_August_September_October_November_December".split("_"), ordinal(t){const e=[ "th", "st", "nd", "rd" ]; const n=t%100;return `[${t}${e[(n-20)%10]||e[n]||e[0]}]`;} }; const m=function(t, e, n){const r=String(t);return !r||r.length>=e?t:`${Array.from({ length: e+1-r.length }).join(n)}${t}`;}; const n=36e5; const o="week"; const r="millisecond"; const s="minute"; const t=1e3; const u="hour"; const v={ s:m, z(t){const e=-t.utcOffset(); const n=Math.abs(e); const r=Math.floor(n/60); const i=n%60;return `${(e<=0?"+":"-")+m(r, 2, "0")}:${m(i, 2, "0")}`;}, m:function t(e, n){if (e.date()<n.date()) return -t(n, e);const r=12*(n.year()-e.year())+(n.month()-e.month()); const i=e.clone().add(r, c); const s=n-i<0; const u=e.clone().add(r+(s?-1:1), c);return +(-(r+(n-i)/(s?i-u:u-i))||0);}, a(t){return t<0?Math.ceil(t)||0:Math.floor(t);}, p(t){return { M:c, y:h, w:o, d:a, D:d, h:u, m:s, s:i, ms:r, Q:f }[t]||String(t||"").toLowerCase().replace(/s$/, "");}, u(t){return void 0===t;} }; const y=/\[([^\]]+)\]|Y{1,4}|M{1,4}|D{1,2}|d{1,4}|H{1,2}|h{1,2}|a|A|m{1,2}|s{1,2}|Z{1,2}|SSS/g;D[g]=M;const O=v; const p=function(t){return t instanceof b;}; const S=function t(e, n, r){let i;if (!e) return g;if (typeof e==="string"){const s=e.toLowerCase();D[s]&&(i=s), n&&(D[s]=n, i=s);const u=e.split("-");if (!i&&u.length>1) return t(u[0]);} else {const a=e.name;D[a]=e, i=a;} return !r&&i&&(g=i), i||!r&&g;}; const w=function(t, e){if (p(t)) return t.clone();const n=typeof e==="object"?e:{};return n.date=t, n.args=arguments, new b(n);};O.l=S, O.i=p, O.w=function(t, e){return w(t, { locale:e.$L, utc:e.$u, x:e.$x, $offset:e.$offset });};var b=function(){function M(t){this.$L=S(t.locale, null, !0), this.parse(t);} const m=M.prototype;return m.parse=function(t){this.$d=function(t){const e=t.date; const n=t.utc;if (e===null) return new Date(Number.NaN);if (O.u(e)) return new Date;if (e instanceof Date) return new Date(e);if (typeof e==="string"&&!/Z$/i.test(e)){const r=e.match($);if (r){const i=r[2]-1||0; const s=(r[7]||"0").slice(0, 3);return n?new Date(Date.UTC(r[1], i, r[3]||1, r[4]||0, r[5]||0, r[6]||0, s)):new Date(r[1], i, r[3]||1, r[4]||0, r[5]||0, r[6]||0, s);}} return new Date(e);}(t), this.$x=t.x||{}, this.init();}, m.init=function(){const t=this.$d;this.$y=t.getFullYear(), this.$M=t.getMonth(), this.$D=t.getDate(), this.$W=t.getDay(), this.$H=t.getHours(), this.$m=t.getMinutes(), this.$s=t.getSeconds(), this.$ms=t.getMilliseconds();}, m.$utils=function(){return O;}, m.isValid=function(){return !(this.$d.toString()===l);}, m.isSame=function(t, e){const n=w(t);return this.startOf(e)<=n&&n<=this.endOf(e);}, m.isAfter=function(t, e){return w(t)<this.startOf(e);}, m.isBefore=function(t, e){return this.endOf(e)<w(t);}, m.$g=function(t, e, n){return O.u(t)?this[e]:this.set(n, t);}, m.unix=function(){return Math.floor(this.valueOf()/1e3);}, m.valueOf=function(){return this.$d.getTime();}, m.startOf=function(t, e){const $=function(t, e){return O.w(n.toDate()[t].apply(n.toDate("s"), (r?[ 0, 0, 0, 0 ]:[ 23, 59, 59, 999 ]).slice(e)), n);}; const f=O.p(t); const l=function(t, e){const i=O.w(n.$u?Date.UTC(n.$y, e, t):new Date(n.$y, e, t), n);return r?i:i.endOf(a);}; const M=this.$M; const m=this.$D; let n=this; let r=!!O.u(e)||e; const v=`set${this.$u?"UTC":""}`; const y=this.$W;switch (f){case a: {;
        } case d: {return $(`${v}Hours`, 0);
            } case c: {return r?l(1, M):l(0, M+1);
            } case h: {return r?l(1, 0):l(31, 11);
            } case i: {return $(`${v}Milliseconds`, 3);
            } case o: {const g=this.$locale().weekStart||0; const D=(y<g?y+7:y)-g;return l(r?m-D:m+(6-D), M);
            } case s: {return $(`${v}Seconds`, 2);
            } case u: {return $(`${v}Minutes`, 1);
            } default: {return this.clone();
            }}}, m.endOf=function(t){return this.startOf(t, !1);}, m.$set=function(t, e){const o=O.p(t); const $=o===a?this.$D+(e-this.$W):e; const f=`set${this.$u?"UTC":""}`; let n; const l=(n={}, n[a]=`${f}Date`, n[d]=`${f}Date`, n[c]=`${f}Month`, n[h]=`${f}FullYear`, n[u]=`${f}Hours`, n[s]=`${f}Minutes`, n[i]=`${f}Seconds`, n[r]=`${f}Milliseconds`, n)[o];if (o===c||o===h){const y=this.clone().set(d, 1);y.$d[l]($), y.init(), this.$d=y.set(d, Math.min(this.$D, y.daysInMonth())).$d;} else l&&this.$d[l]($);return this.init(), this;}, m.set=function(t, e){return this.clone().$set(t, e);}, m.get=function(t){return this[O.p(t)]();}, m.add=function(r, f){let d; const l=this;r=Number(r);const $=O.p(f); const y=function(t){const e=w(l);return O.w(e.date(e.date()+Math.round(t*r)), l);};if ($===c) return this.set(c, this.$M+r);if ($===h) return this.set(h, this.$y+r);if ($===a) return y(1);if ($===o) return y(7);const M=(d={}, d[s]=e, d[u]=n, d[i]=t, d)[$]||1; const m=this.$d.getTime()+r*M;return O.w(m, this);}, m.subtract=function(t, e){return this.add(-1*t, e);}, m.format=function(t){const e=this; const n=this.$locale();if (!this.isValid()) return n.invalidDate||l;const f=n.meridiem; const $=f||function(t, e, n){const r=t<12?"AM":"PM";return n?r.toLowerCase():r;}; const a=this.$M; const c=n.months; const d=function(t){return O.s(s%12||12, t, "0");}; const h=function(t, n, i, s){return t&&(t[n]||t(e, r))||i[n].slice(0, s);}; const i=O.z(this); const o=n.weekdays; let r=t||"YYYY-MM-DDTHH:mm:ssZ"; let s=this.$H; const u=this.$m;return r.replaceAll(y, ((t, r) =>{return r||function(t){switch (t){case "a": {return $(s, u, !0);
        } case "A": {return $(s, u, !1);
            } case "D": {return e.$D;
            } case "d": {return String(e.$W);
            } case "DD": {return O.s(e.$D, 2, "0");
            } case "dd": {return h(n.weekdaysMin, e.$W, o, 2);
            } case "ddd": {return h(n.weekdaysShort, e.$W, o, 3);
            } case "dddd": {return o[e.$W];
            } case "H": {return String(s);
            } case "h": {return d(1);
            } case "HH": {return O.s(s, 2, "0");
            } case "hh": {return d(2);
            } case "M": {return a+1;
            } case "m": {return String(u);
            } case "MM": {return O.s(a+1, 2, "0");
            } case "mm": {return O.s(u, 2, "0");
            } case "MMM": {return h(n.monthsShort, a, c, 3);
            } case "MMMM": {return h(c, a);
            } case "s": {return String(e.$s);
            } case "ss": {return O.s(e.$s, 2, "0");
            } case "SSS": {return O.s(e.$ms, 3, "0");
            } case "YY": {return String(e.$y).slice(-2);
            } case "YYYY": {return O.s(e.$y, 4, "0");
            } case "Z": {return i;
            }} return null;}(t)||i.replace(":", "");}));}, m.utcOffset=function(){return 15*-Math.round(this.$d.getTimezoneOffset()/15);}, m.diff=function(r, d, l){let $; const y=this; const M=O.p(d); const m=w(r); const v=(m.utcOffset()-this.utcOffset())*e; const g=this-m; const D=function(){return O.m(y, m);};switch (M){case a: {$=(g-v)/864e5;break;
        } case c: {$=D();break;
            } case f: {$=D()/3;break;
            } case h: {$=D()/12;break;
            } case i: {$=g/t;break;
            } case o: {$=(g-v)/6048e5;break;
            } case s: {$=g/e;break;
            } case u: {$=g/n;break;
            } default: {$=g;
            }} return l?$:O.a($);}, m.daysInMonth=function(){return this.endOf(c).$D;}, m.$locale=function(){return D[this.$L];}, m.locale=function(t, e){if (!t) return this.$L;const n=this.clone(); const r=S(t, e, !0);return r&&(n.$L=r), n;}, m.clone=function(){return O.w(this.$d, this);}, m.toDate=function(){return new Date(this.valueOf());}, m.toJSON=function(){return this.isValid()?this.toISOString():null;}, m.toISOString=function(){return this.$d.toISOString();}, m.toString=function(){return this.$d.toUTCString();}, M;}(); const _=b.prototype;return w.prototype=_, [ [ "$ms", r ], [ "$s", i ], [ "$m", s ], [ "$H", u ], [ "$W", a ], [ "$M", c ], [ "$y", h ], [ "$D", d ] ].forEach(((t) =>{_[t[1]]=function(e){return this.$g(e, t[0], t[1]);};})), w.extend=function(t, e){return t.$i||(t(e, b, w), t.$i=!0), w;}, w.locale=S, w.isDayjs=p, w.unix=function(t){return w(1e3*t);}, w.en=D[g], w.Ls=D, w.p={}, w;}));
    }, (modId) => {const map = {}; return __REQUIRE__(map[modId], modId); });
    return __REQUIRE__(1_691_668_914_749);
})();
// miniprogram-npm-outsideDeps=[]
// # sourceMappingURL=index.js.map